### ISSUE TITLE
IE11 issue

### ISSUE THREAD

**Issue by OlgaLevanova** [morkro/vue-a11y-dialog#21]
Hi there,

File vue-a11y-dialog.js has 2 arrow functions and IE11 doesn't understand them. When I replace them with normal functions everything works perfect. Can you pleace fix this in repo? Thanks

**Comment by morkro** [comment]
Hey @OlgaLevanova, thanks for pointing this out. 

I changed all arrow functions to normal functions to allow support for IE11. The release [`0.5.1`](https://github.com/morkro/vue-a11y-dialog/releases/tag/0.5.1) has been published and you can upgrade.
