### ISSUE TITLE
issue rendering two dialogs on the same page.

### ISSUE THREAD

**Issue by renatodeleao** [morkro/vue-a11y-dialog#8]
Thanks for the wrapper, i'm fan of the original plugin, and will be of this wrapper for sure :) 

This sounds like a dumb question (and probably is), but i want to render `[2..n]` dialogs in one page. For demo purposes i went with 2, and currently it's only rendering the last one. For the first i'm getting the following error for the first : 

```
DOMException: Failed to execute 'showModal' on 'HTMLDialogElement': The element is not in a Document.
```
### [Demo link](https://codesandbox.io/s/6wjq0r78kr)

My suspicions go to the `portal-target`. Since we're using the "html" version of it i suspect we don't get the [`multiple` option](https://linusborg.github.io/portal-vue/#/guide?id=showing-content-from-multiple-portals-in-one-target) that comes with the component version `<portal-target multiple>`, but i might be wrong, so I wanted to get your input on this.

Thanks for your time! ✋

**Comment by morkro** [comment]
Hey @renatodeleao! Thanks for pointing this out, I am aware of that issue as well. I _believe_ this is fixed with an upcoming version of PortalVue and I am kinda waiting for that update to be honest. If this issue isn't resolved any time soon, I will have to either put a warning in the README or suggest solutions.

In one of my projects, I've [overcome this problem](https://github.com/morkro/happy-plants/blob/master/src/components/AppDialog.vue) by wrapping `vue-a11y-dialog` in another component which uses again `<portal>`s to place content. By that I am able to use multiple dialogs in one screen, while technically only using one dialog.

**Comment by renatodeleao** [comment]
that's a clever trick, thanks for sharing!
I've saw the issue on PortalVue, i'll keep an eye on it as well!

Cheers!

**Comment by renatodeleao** [comment]
I see, but as Linus has pointed `target-el` is ["half-assed implementation"](https://github.com/LinusBorg/portal-vue/issues/163#issuecomment-445993758) so i was just wondering if there was any special reason behind this choice.

Personally haven't found any styling/accessibility issues rendering portals inside the app, I just have an extra wrapper for content where the accessibility attributes can be toggled. 


```HTML
<!--App.vue-->

<template>
 <div id="app">
   <div id="wrapper" aria-attributes>
      <router-view />
   </div>

    <!-- portal targets -->
    <portal-target name="destination1" />
    <portal-target name="destination2" />
  </div>
<template>
```

But as i've said, i was just curious, thanks you for your time man!

**Comment by renatodeleao** [comment]
That's is correct, but the second argument of `A11yDialog` constructor is an option to specify who is the [_content container_](https://github.com/edenspiekermann/a11y-dialog#javascript-instantiation) (by default the siblings of dialog). 

You already provide a prop to specify this element `appRoot`, and it isn't required to be "#app".  This combined with a simple computedProp would allows you to **optionally** use the `<portal-target>` instead of `target-el` without any accessibility issue.

Here's your documentation example re-written to encapsulate all the thoughts of this thread
```vue
<template>
  <div id="app"> 
    <main id="content-wrapper-for-accessiblity">
      <!-- ... in real world, this would be router-view -->
      <button type="button" @click="openDialog">
        Open dialog
      </button>

      <a11y-dialog
        id="app-dialog"
        app-root="#content-wrapper-for-accessiblity"
        dialog-root="#dialog-root"
        @dialog-ref="assignDialogRef"
        portal-target="my-dialogs"
        render-mode="fake-inside-prop"
      >
        <h1 slot="title">Your dialog title</h1>
        <div>
          <p>Your content</p>
        </div>
      </a11y-dialog>
    </main>

    <portal-target name="my-dialogs" multiple />
  </div>
</template>
```

Now this is just an alternative, a cheap one in terms of code. I know that with `vue-portal 2.0` fortunately these will be problems of the past.

Sorry if i'm being annoying, i'm just a nerd and can't avoid a good positive discussion around code 😄

**Comment by morkro** [comment]
Hey @renatodeleao, just wanted to give you a quick update that  PortalVue@2 is out and the newly introduced `MountingPortal` fixes the issue! I have a [new release](https://github.com/morkro/vue-a11y-dialog/pull/11) coming up either today or tomorrow. Then you will be able to use multiple portals as in your initial demo.

**Comment by morkro** [comment]
I've just released a new version, do you mind checking if it works for you?

**Comment by renatodeleao** [comment]
@morkro works like charm, I leave here the updated [demo for reference](https://codesandbox.io/s/1o23zlp3k4).

Thanks!
